# -*- indent-tabs-mode: nil -*- # vi: set expandtab:
#
# ============LICENSE_START=======================================================
# Copyright (c) 2017-2018 AT&T Intellectual Property. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.

# File: policy_handler_sample_app_config.yaml contains sample application config for policy-handler of DCAE Controller

application_config:
  policy_handler :
    # parallelize the getConfig queries to policy-engine on each policy-update notification
    thread_pool_size : 4

    # parallelize requests to policy-engine and keep them alive
    pool_connections : 20

    # list of policyName prefixes (filters) that DCAE-Controller handles (=ignores any other policyName values)
    scope_prefixes : ["DCAE.Config_"]

    # retry to getConfig from policy-engine on policy-update notification
    policy_retry_count : 5
    policy_retry_sleep : 5

    # config of automatic catch_up for resiliency
    catch_up :
        # interval in seconds on how often to call automatic catch_up
        # example: 1200 is 20*60 seconds that is 20 minutes
        interval : 1200
        # max_skips is the maximal number of times the auto catch_up can be skipped
        # to reduce sending of identically the same messages to the deployment-handler
        # example: if nothing changes in policy-engine
        #          the policy-handler will still send the identicall cathc_up message
        #          to deployment handler roughly every (max_skips + 1) * interval seconds
        #          instead of sending the changed message every interval seconds
        # in this case of max_skips = 5 the catch_up message will be sent
        #          roughly every 2 hours = (5+1) * 1200 = 6 * 20 * 60 seconds = 2 * 60 * 60
        max_skips : 5

    # policy-engine config
    # These are the url of and the auth for the external system, namely the policy-engine (PDP).
    # We obtain that info manually from PDP folks at the moment.
    # In long run we should figure out a way of bringing that info into consul record
    #    related to policy-engine itself.
    policy_engine :
        url : "{{ YOUR_POLICY_ENGINE_URL }}"
        path_pdp : "/pdp/"
        path_api : "/pdp/api/"
        headers :
            Accept : "application/json"
            "Content-Type" : "application/json"
            ClientAuth : "Basic {{ YOUR_POLICY_ENGINE_CLIENT_AUTH }}"
            Authorization : "Basic {{ YOUR_POLICY_ENGINE_AUTHORIZATION }}"
            Environment : "{{ YOUR_POLICY_ENGINE_ENVIRONMENT }}"
        target_entity : "policy_engine"

    # deploy_handler config
    #    changed from string "deployment_handler" in 2.3.1 to structure in 2.4.0
    deploy_handler :
        # name of deployment-handler service used by policy-handler for logging
        target_entity : "deployment_handler"
        # url of the deployment-handler service for policy-handler to direct the policy-updates to
        #   - expecting dns to resolve the name deployment_handler to ip address
        url : "http://deployment_handler:8188"
